s3:
  input_bucket_name: "s3://mlflow-sagemaker-us-east-1-750573229682/xgb_housing/inout_csv/"
  input_filename: "california_housing.csv"
  output_bucket_name: "s3://mlflow-sagemaker-us-east-1-750573229682/xgb_housing/processed_csv/"
  output_filename: "s3://mlflow-sagemaker-us-east-1-750573229682/xgb_housing/processed_csv/"

sagemaker:
  mlflow_tracking_uri: "arn:aws:sagemaker:us-east-1:750573229682:mlflow-tracking-server/mlflow-tracking-server-sagemaker-poc"
  experiment_name: "experiment_name" 
  model_name: "xgb-housing-model"


